version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r tests/requirements.txt
      - apt-get install -y jq

  pre_build:
    commands:
      - echo "Setting up the environment..."
      - export PYTHONPATH=$PYTHONPATH:$(pwd)  # Set PYTHONPATH to include the current directory
      - echo "Environment setup complete."
      - echo "Fetching commit ID and branch name..."
      # The following git commands may fail in a CodePipeline environment, consider using env vars from CodePipeline
      - export GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD || echo $CODEBUILD_SOURCE_VERSION)
      - export GIT_COMMIT=$(git rev-parse HEAD || echo $CODEBUILD_RESOLVED_SOURCE_VERSION)

  build:
    commands:
      - echo "Running pytest tests..."
      - pytest --junitxml=reports/results.xml

  post_build:
    commands:
      - echo "Build phase complete."

reports:
  pytest_report:
    files:
      - results.xml
    base-directory: reports/
    file-format: JUNITXML