version: 0.2
env:
  variables:
    ALLURE_RESULTS_DIR: "/tmp/allure-results"
    RAW_BUCKET: "raw-s3-conference-user-9fe23ed6-7re1fbmf"
    CURATED_BUCKET: "curated-s3-conference-user-9fe23ed6-7re1fbmf"
    CLEAN_BUCKET: "clean-s3-conference-user-9fe23ed6-7re1fbmf"
    SNS_TOPIC_ARN: "arn:aws:sns:eu-west-1:087559609246:etl-notifications-conference-user-9fe23ed6"
    LAMBDA_CLEAN_CURATED_FUNCTION_NAME: "clean_curated_lmb-conference-user-9fe23ed6"
    LAMBDA_RAW_CLEAN_FUNCTION_NAME: "raw_clean_lmb-conference-user-9fe23ed6"
    LAMBDA_DATA_GENERATOR_FUNCTION_NAME: "data_generator_lmb-conference-user-9fe23ed6"
    DATA_GENERATOR_FUNCTION_NAME: "data_generator-conference-user-9fe23ed6"
    ALLURE_REPORT_BUCKET: "allure-reports-conference-user-9fe23ed6"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r tests/requirements.txt
      - apt-get install -y jq

  pre_build:
    commands:
      - cat buildspec.yml
      - echo "Setting up the environment..."
      - export PYTHONPATH=$PYTHONPATH:$(pwd)  # Set PYTHONPATH to include the current directory
      - echo "Environment setup complete."
      - echo "Fetching commit ID and branch name..."
      # The following git commands may fail in a CodePipeline environment, consider using env vars from CodePipeline
      - export GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD || echo $CODEBUILD_SOURCE_VERSION)
      - export GIT_COMMIT=$(git rev-parse HEAD || echo $CODEBUILD_RESOLVED_SOURCE_VERSION)

  build:
    commands:
      - echo "Running pytest tests..."
      - pytest tests --alluredir=$ALLURE_RESULTS_DIR

  post_build:
  commands:
      - echo "Generating Allure report"
      - allure generate $ALLURE_RESULTS_DIR -o allure-report --clean
      - echo "Downloading previous history"
      - aws s3 sync s3://$ALLURE_REPORT_BUCKET/history/ allure-report/history/ || true
      - echo "Uploading Allure report to S3"
      - aws s3 sync allure-report s3://$ALLURE_REPORT_BUCKET/latest/ --delete
      - echo "Updating Allure history"
      - aws s3 sync allure-report/history s3://$ALLURE_REPORT_BUCKET/history/ --delete

artifacts:
  files:
    - '**/*'
  name: test-output
  base-directory: allure-report

reports:
  pytest_report:
    files:
      - results.xml
    base-directory: reports/
    file-format: JUNITXML