version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r tests/requirements.txt
      - pip install allure-pytest
  pre_build:
    commands:
      - echo "Setting up test environment"
  build:
    commands:
      - echo "Running tests"
      - pytest tests --alluredir=$ALLURE_RESULTS_DIR
  post_build:
    commands:
      - echo "Generating Allure report"
      - allure generate $ALLURE_RESULTS_DIR -o allure-report --clean
artifacts:
  files:
    - '**/*'
  name: test-output
  base-directory: allure-report