name: Terraform Apply ETL Infrastructure

on:
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  issues: write

jobs:
  terraform_apply_etl:
    name: Terraform Apply ETL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Make setup_infrastructure.sh executable
      run: chmod +x ./scripts/setup_infrastructure.sh

    - name: Run setup_infrastructure.sh
      run: ./scripts/setup_infrastructure.sh ${{ github.actor }}

    - name: Terraform Init and Apply
      working-directory: ./iac/etl
      run: |
        terraform init -input=false
        terraform apply -auto-approve

    - name: Install Dashboard dependencies
      run: pip install -r scripts/requirements.txt

    - name: Create QuickSight Dashboard
      run: python scripts/create_quicksight_dashboard.py
