name: Terraform Plan Check

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:  # To ensure that pull requests are also checked

permissions:
  contents: read
  issues: write

jobs:
  terraform_plan_check:
    name: Terraform Plan Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Run setup_infrastructure.sh
        run: ./scripts/setup_infrastructure.sh ${{ github.actor }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

      # Initialize Terraform with Local Backend for Backend Infrastructure
      - name: Initialize Terraform with Local Backend for Backend
        working-directory: ./iac/backend
        run: |
          echo "Using local backend for Terraform."
          cat > backend.tf <<EOF
          terraform {
            backend "local" {
              path = "./terraform.tfstate"
            }
          }
          EOF
          terraform init

      - name: Terraform Plan for Backend
        working-directory: ./iac/backend
        run: terraform plan

      # Initialize Terraform with Local Backend for CICD Infrastructure
      - name: Initialize Terraform with Local Backend for CICD
        working-directory: ./iac/cicd
        run: |
          echo "Using local backend for Terraform."
          cat > backend.tf <<EOF
          terraform {
            backend "local" {
              path = "./terraform.tfstate"
            }
          }
          EOF
          terraform init

      - name: Terraform Plan for CICD
        working-directory: ./iac/cicd
        run: terraform plan

      # Initialize Terraform with Local Backend for ETL Infrastructure
      - name: Initialize Terraform with Local Backend for ETL
        working-directory: ./iac/etl
        run: |
          echo "Using local backend for Terraform."
          cat > backend.tf <<EOF
          terraform {
            backend "local" {
              path = "./terraform.tfstate"
            }
          }
          EOF
          terraform init

      - name: Terraform Plan for ETL
        working-directory: ./iac/etl
        run: terraform plan
